echo -e '\e[40m\e[92m'
echo -e '								'
echo -e '           ,ggg,                                              	'
echo -e '          dP""8I   ,dPYb,                                     	'
echo -e '         dP   88   IP'`Yb                                     	'
echo -e '        dP    88   I8  8I  gg                                 	'
echo -e '       ,8'    88   I8  8'  ""                                 	'
echo -e '       d88888888   I8 dP   gg    ,ggg,,ggg,     ,gggg,gg      	'
echo -e ' __   ,8"     88   I8dP    88   ,8" "8P" "8,   dP"  "Y8I      	'
echo -e 'dP"  ,8P      Y8   I8P     88   I8   8I   8I  i8'    ,8I      	'
echo -e 'Yb,_,dP       `8b,,d8b,_ _,88,_,dP   8I   Yb,,d8,   ,d8b,     	'
echo -e ' "Y8P"         `Y88P'"Y888P""Y88P'   8I   `Y8P"Y8888P"`Y8     	'
echo -e '                                                              	'
echo -e '                                                              	'
echo -e ' ,ggg,         ,gg                                            	'
echo -e 'dP""Y8a       ,8P        ,dPYb,                               	'
echo -e 'Yb, `88       d8'        IP'`Yb                               	'
echo -e ' `"  88       88         I8  8I                               	'
echo -e '     88       88         I8  8'                               	'
echo -e '     I8       8I ,ggg,   I8 dP   ,ggg,    ,gggggg,  gg     gg 	'
echo -e '     `8,     ,8'i8" "8i  I8dP   i8" "8i   dP""""8I  I8     8I 	'
echo -e '      Y8,   ,8P I8, ,8I  I8P    I8, ,8I  ,8'    8I  I8,   ,8I 	'
echo -e '       Yb,_,dP  `YbadP' ,d8b,_  `YbadP' ,dP     Y8,,d8b, ,d8I 	'
echo -e '        "Y8P"  888P"Y8888P'"Y88888P"Y8888P      `Y8P""Y88P"888	'
echo -e '                                                         ,d8I'	'
echo -e '                                                       ,dP'8I 	'
echo -e '                                                      ,8"  8I 	'
echo -e '                                                      I8   8I 	'
echo -e '                                                      `8, ,8I 	'
echo -e '                                                       `Y8P"  	'
echo -e '								'
echo -e '\e[0m'
